name: Build attendance & visuals

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Aggregate & Render
        run: python -u scripts/aggregate.py

      - name: Commit changes if any
        run: |
          git add -A
          CHANGES="$(git diff --cached --name-only | grep -E '^(data/|assets/)' || true)"
          if [[ -n "${CHANGES}" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "build: update attendance visuals [skip ci]"
            git push
          else
            echo "No changes in data/ or assets/, skipping commit."
          fi

